### ISSUE TITLE
Error: Module version mismatch. Expected 46, got 59.

### ISSUE THREAD

**Issue by 1e1001** [vesteraas/node-pitft#12]
I followed all of the not very well documented download instructions, installing Cairo, pitft, and all the modules it needs, but I keep getting the same version mismatch. It looks like the pitft module uses an older version of bindings.js (or maybe even node.js). Here is the error log:

    /home/pi/Documents/nodejs/node-modules/bindings/bindings.js:88
            throw e
            ^
    
    Error: Module version mismatch. Expected 46, got 59.
        at Error (native)
        at Object.Module._extentions..node (module.js:434:18)
        at Module.load (module.js:343:32)
        at Function.Module._load (module.js:300:12)
        at Module.require (module.js:353:17)
        at require (internal/module.js:12:17)
        at bindings (/home/pi/Documents/nodejs/node-modules/bindings/bindings.js:81:44)
        at Object.<anonymous> (/home/pi/Documents/nodejs/node-modules/pitft/pitft.js:1:97)
        at Module._compile (module.js:409:26)
        at Object.Module._extensions.js (module.js:416:10)

**Comment by 1e1001** [comment]
Just as a side note: I am using a Raspberry Pi 3 model B running raspbian stretch 2017-11-29. and the 3.5" pitft plus

**Comment by vesteraas** [comment]
I've not managed to reproduce this issue.  Closing this, as I have not received more reports similar to this.
